### ISSUE TITLE
Links down

### ISSUE THREAD

**Issue by alexg93333** [Mushroomcat9998/PaddleOCR#1]
Mushroomcat9998/PaddleOCR/tree/main/deploy/lite/readme_en.md

1.1 Prepare the cross-compilation environment
2.Linux <Link down 404>

Can you please reupload the link? Because I don't know how to prepare my platform. As a result, I can't perform the step "make -j", it give me these errors:

In file included from cls_process.cc:15:
./cls_process.h:17:10: fatal error: 'cstring' file not found
In file included from db_post_process.cc:15:
./db_post_process.h:17:10: fatal error: 'math.h' file not found
In file included from crnn_process.cc:15:
./crnn_process.h:17:10: fatal error: 'cstring' file not found
ocr_db_crnn.cc:15:10: fatal error: 'chrono' file not found
#include <cstring>#include <math.h>
         ^~~~~~~~
#include <chrono>
         ^~~~~~~~

         ^~~~~~~~~
In file included from clipper.cpp:55:
./clipper.hpp:52:10: fatal error: 'vector' file not found

**Comment by Mushroomcat9998** [comment]
You can follow [this link](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/lite/readme.md) in the original repo [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR). Thanks for watching my custom repo.

**Comment by alexg93333** [comment]
Thanks for the quick answer, unfortunately the links on the site don't work anymore. Do you remember by chance what to do to prepare all the c++ libraries for the "make -j" command?

**Comment by Mushroomcat9998** [comment]
I don't work with c++ libraries, just python. It will help if you search for more issues in the original repo.

**Comment by alexg93333** [comment]
Thanks a lot for the link! Have a nice day
