### ISSUE TITLE
Paddle OCR Text detection Model Evaluation take too much time 

### ISSUE THREAD

**Issue by kokul93** [Mushroomcat9998/PaddleOCR#3]
I am training PaddleOCR for Tamil language and when I train the model with 70 images for training and 24 images for evaluation.

After 1st epoch the model take more time (More than 5 hrs) on Evaluation

**Comment by Mushroomcat9998** [comment]
I have no idea why it takes a long time for Text detection Model Evaluation with PaddleOCR, but I think your dataset when training has some problems. I have often used [DBNet](https://github.com/WenmuZhou/DBNet.pytorch) repo for training Text Detection Model, you can try it if you find it interesting.
Thanks for watching my custom repo
