### ISSUE TITLE
LatinV3 performance for european languages

### ISSUE THREAD

**Issue by jochennaumann** [Mushroomcat9998/PaddleOCR#4]
I tried the LatinV3 for european languages like german or czech. The recognition quality is very poor or recognition is not working at all with the special characters in these languages like öäiéá etc. 
Will there be a LatinV4 model in the future that delivers better quality?
Or are there specialized models for each language that I need to download somewhere?
The english V4 model is very good! Would love to see an equally good LatinV4 model :-)

**Comment by Mushroomcat9998** [comment]
You should follow the [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR). I find that PP-OCRv4 supports the multilingual model ([ref](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_ch/multi_languages.md#%E8%AF%AD%E7%A7%8D%E7%BC%A9%E5%86%99)) quite well, so you can update the paddleocr for your own testing.
Thanks for watching my custom repo.
